# Generated by Django 4.0.6 on 2022-07-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0002_rename_customers_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
