# Generated by Django 4.0.6 on 2022-07-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0007_remove_order_tag_product_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
